version: "3.8"

services:
  dataflow:
    build: ./dataflow
    container_name: dataflow_service

  quant:
    build: ./quant
    container_name: quant_service
    depends_on:
      - dataflow

  riskops:
    build: ./riskops
    container_name: riskops_service
    depends_on:
      - quant

  execconnect:
    build: ./execconnect
    container_name: execconnect_service
    depends_on:
      - riskops
